spring:
  application:
    name: ZuulServer
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://localhost:9300/        

server:
  port: 9191

zuul:
  routes:
    login:
      path : /login/userDetails
      service-id : LoginMS
    addDefects:
      path: /defects/addDefect
      service-id: DefectMS
    getDefects:
      path: /defects/getAllDefects
      service-id: DefectMS
    updateDefects:
      path: /defects/updateDefect/*
      service-id: DefectMS
   

    