zuul:
  routes:
    login:
      path: /login/**
      strip-prefix: false
      serviceId: LoginMS
eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://localhost:9200/eureka